AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FirstSkillDevelopment:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: first_skill_development/
      Handler: hello_world.handler
      Runtime: python3.9
      Architectures:
        - x86_64

  ColorPicker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: color_picker/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  Trivia:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: trivia/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  CityGuide:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: city_guide/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
